import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

test("has no Sites or Cloudflare runtime dependency", async () => {
  const [packageJson, nextConfig, dockerfile, dockerCompose, page, styles] = await Promise.all([
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../next.config.ts", import.meta.url), "utf8"),
    readFile(new URL("../Dockerfile", import.meta.url), "utf8"),
    readFile(new URL("../docker-compose.yml", import.meta.url), "utf8"),
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);

  assert.match(packageJson, /"next": "16\.2\.6"/);
  assert.doesNotMatch(packageJson, /vinext|wrangler|cloudflare|drizzle/i);
  assert.match(nextConfig, /output: "standalone"/);
  assert.match(dockerfile, /ENV NEXO_LAB_DB_PATH=\/app\/data\/nexo-lab\.sqlite/);
  assert.match(dockerfile, /ENV NEXO_LAB_BOOTSTRAP_EMAIL=jablasal@unizar\.es/);
  assert.match(dockerCompose, /NEXO_LAB_DB_PATH: \/app\/data\/nexo-lab\.sqlite/);
  assert.match(dockerCompose, /NEXO_LAB_BOOTSTRAP_PASSWORD/);
  assert.match(dockerCompose, /nexo_lab_data:\/app\/data/);
  assert.doesNotMatch(page, /Todo el ecosistema docente/);
  assert.match(page, /semesterDisplayTitle/);
  assert.match(page, /Semestre \$\{semester\.number\}/);
  assert.match(page, /Curso \{shortAcademicYear\}/);
  assert.match(page, /· Curso/);
  assert.match(page, /overview-semester-focus/);
  assert.match(page, /calendar-semester-focus/);
  assert.match(styles, /\.semester-focus h1/);
  assert.match(styles, /\.overview-semester-focus \{ min-height: clamp\(280px/);
  assert.match(styles, /\.semester-focus h1 > small/);
  assert.match(page, /Sesiones por grado/);
  assert.match(page, /Sesiones por profesor/);
  assert.match(page, /<h2>Asignaturas<\/h2>/);
  assert.match(page, /Profesor editor/);
  assert.match(page, /Sesiones por profesor/);
  assert.match(page, /subjectTeacherSessionCounts/);
  assert.match(page, /overview-subject-summary-table/);
  assert.match(page, /subjectSummarySort/);
  assert.match(page, /Ordenar por/);
  assert.match(page, /<option value="name">Nombre<\/option>/);
  assert.match(page, /<option value="code">Código<\/option>/);
  assert.match(page, /overview-subject-editor-chip/);
  assert.match(page, /overview-subject-session-chip/);
  assert.match(page, /overview-subject-unassigned-count/);
  assert.match(styles, /\.overview-subject-summary-table/);
  assert.match(styles, /\.overview-subject-unassigned-count\.has-sessions/);
  assert.match(page, /teacherSessionCounts/);
  assert.match(page, /unassignedTeacherSessionCount/);
  assert.match(page, /function UnassignedTeacherSessionCount/);
  assert.match(page, /\(\{count\} s\/prof\)/);
  assert.match(page, /degreeUnassignedTeacherSessionCounts/);
  assert.match(page, /subjectUnassignedTeacherSessionCounts/);
  assert.match(page, /degreeUnassignedTeacherSessionCount/);
  assert.match(page, /subjectUnassignedTeacherSessionCount/);
  assert.match(styles, /\.unassigned-teacher-session-count/);
  assert.match(page, /overview-teacher-table/);
  assert.match(page, /function OverviewTeacherSessions/);
  assert.match(page, /sessionsByTeacher/);
  assert.match(page, /expandedTeacherKeys/);
  assert.match(page, /overview-teacher-session-row/);
  assert.match(styles, /\.overview-teacher-table/);
  assert.match(styles, /\.overview-teacher-data-row\.expanded/);
  assert.match(page, /semesterFromDate\(session\.sessionDate\) === selectedSemester/);
  assert.match(page, /left\.name\.localeCompare\(right\.name, "es", \{ sensitivity: "base" \}\)/);
  assert.match(page, /overview-degree-item/);
  assert.match(page, /Asignaturas de \$\{degree\.name\}/);
  assert.match(page, /subjectSessionCounts/);
  assert.match(page, /sessionsBySubject/);
  assert.match(page, /function OverviewSubjectSessions/);
  assert.match(page, /overview-subject-item/);
  assert.match(page, /function OverviewGroupedSubjectSessions/);
  assert.match(page, /groupedSubjectIds/);
  assert.match(page, /Por subgrupos/);
  assert.match(page, /Selec\. subgrupos/);
  assert.match(page, /function firstUnassignedSessionPerSubgroup/);
  assert.match(page, /session\.practiceId !== null/);
  assert.match(page, /firstSessionBySubgroup\.has\(subgroup\)/);
  assert.match(page, /Seleccionar la primera sesión sin práctica de cada subgrupo de \$\{subject\.name\}/);
  assert.match(page, /toggleFirstUnassignedSubgroups\(subjectSessions\)/);
  assert.match(page, /Agrupar las sesiones de \$\{subject\.name\} por subgrupos/);
  assert.match(page, /Sesiones de la asignatura agrupadas por subgrupo y horario/);
  assert.match(page, /sessionsByGroup/);
  assert.match(page, /const groupKey = groupCode \|\| "__unassigned__"/);
  assert.match(page, /schedulesByKey/);
  assert.match(page, /dayTypes\.join\("\/"\)/);
  assert.match(page, /scheduleSummary/);
  assert.match(page, /groupUnassignedTeacherSessionCount = group\.sessions\.filter\(\(session\) => session\.teacherId === null\)\.length/);
  assert.match(page, /group\.sessions\.length\}<UnassignedTeacherSessionCount count=\{groupUnassignedTeacherSessionCount\}/);
  assert.match(page, /function OverviewTeacherGroupedSubjectSessions/);
  assert.match(page, /teacherGroupedSubjectIds/);
  assert.match(page, /Por profesor/);
  assert.match(page, /Agrupar las sesiones de \$\{subject\.name\} por profesor/);
  assert.match(page, /Sesiones de la asignatura agrupadas por profesor/);
  assert.match(page, /toggleSubjectTeacherGrouping\(subject\.id\)/);
  assert.match(page, /teacherGroupedSubjectIds\.has\(subject\.id\)[\s\S]*?<OverviewTeacherGroupedSubjectSessions/);
  assert.match(styles, /\.overview-session-teacher-group/);
  assert.match(styles, /\.overview-subject-group-toggle/);
  assert.match(styles, /\.overview-subject-toggles/);
  assert.match(styles, /\.overview-session-groups/);
  assert.match(styles, /\.overview-session-group\[open\] \.overview-session-group-chevron/);
  assert.match(page, /calendar-list overview-session-list/);
  assert.match(page, /SessionListColumns session=\{session\}/);
  assert.match(page, /session\.groupCode \? `G\$\{session\.groupCode\}` : "G—"/);
  assert.match(page, /session\.groupCode \? `G\$\{session\.groupCode\}` : "G—"/);
  assert.match(page, /draggedSession\.groupCode \? `G\$\{draggedSession\.groupCode\}` : "G—"/);
  assert.match(page, /function selectOverviewSession/);
  assert.match(page, /function selectOverviewSession\(session: Session, event: ReactMouseEvent<HTMLButtonElement>, selectionScope\?: Session\[\]\)/);
  assert.match(page, /const subjectSessions = selectionScope \?\? sessionsBySubject\.get\(session\.subjectId\) \?\? \[\]/);
  assert.match(page, /onSelect=\{\(session, event\) => onSelect\(session, event, group\.sessions\)\}/);
  assert.match(page, /sessionSelectionRangeIds\(subjectSessions, anchorId, session\.id\)/);
  assert.match(page, /function assignOverviewTeacher/);
  assert.match(page, /function assignOverviewPractice/);
  assert.match(page, /function deleteOverviewSessions/);
  assert.match(page, /function SessionSelectionActions/);
  assert.equal([...page.matchAll(/<SessionSelectionActions/g)].length, 2);
  assert.match(page, /downloadSessionsIcs/);
  assert.match(page, /downloadSessionsPdf/);
  assert.match(page, /downloadSessionsCsv/);
  assert.match(page, /downloadTeachersCsv/);
  assert.match(page, /entity === "teachers"[\s\S]*?Exportar CSV/);
  assert.match(page, /Exportar ICS/);
  assert.match(page, /Exportar PDF/);
  assert.match(page, /downloadSessionsCsv\(semesterSessions, selectedSemester\)/);
  assert.match(page, /panel-head-actions/);
  assert.match(styles, /\.calendar-selection-bar \.export-action/);
  assert.match(page, /function practicesAvailableToSessions/);
  assert.match(page, /session\.degreePracticeIds\?\.map\(Number\)/);
  assert.match(page, /directPracticeIds\.includes\(practice\.id\)/);
  assert.match(page, /Number\(subject\.degreeId\) === Number\(session\.degreeId\)/);
  assert.match(page, /Asignar práctica a la selección/);
  assert.match(page, /Asignar profesor a la selección/);
  assert.equal([...page.matchAll(/if \(event\.key !== "Escape"\) return;/g)].length, 2);
  assert.match(page, /if \(calendarView !== "list"\) return;/);
  assert.match(page, /Esc limpia la selección/);
  assert.match(page, /const subjectSessions = sessionsBySubject\.get\(session\.subjectId\) \?\? \[\]/);
  assert.match(page, /subjectSessions\.slice\(first, last \+ 1\)/);
  assert.match(page, /const subjectSessions = filteredSemesterSessions\.filter\(\(item\) => item\.subjectId === session\.subjectId\)/);
  assert.match(page, /overview-selection-bar active/);
  assert.match(page, /selectedIds\.has\(session\.id\)/);
  assert.match(styles, /\.overview-degree-item\[open\]/);
  assert.match(styles, /\.overview-subject-item\[open\]/);
  assert.match(styles, /\.overview-subject-list/);
  assert.match(styles, /\.overview-session-list\.calendar-list/);
  assert.match(styles, /\.overview-selection-bar/);
  assert.match(styles, /\.calendar-selection-bar\.active \{[\s\S]*?position: fixed;/);
  assert.match(styles, /\.calendar-selection-bar\.active \{[\s\S]*?bottom: 18px;/);
  assert.match(styles, /\.content-frame:has\(\.calendar-selection-bar\.active\)/);
  assert.match(page, /Asignaturas/);
  assert.match(page, /Abreviatura \(opcional\)/);
  assert.match(page, /subject\.abbreviation/);
  assert.match(page, /Código ICS/);
  assert.match(page, /icsCode/);
  assert.doesNotMatch(page, /<span>Curso<\/span>/);
  assert.doesNotMatch(page, /degree\.academicYear/);
  assert.match(page, /Profesores/);
  assert.match(page, /Correo electrónico/);
  assert.match(page, /type="email"/);
  assert.match(page, /Administrador/);
  assert.match(page, /Solo lectura/);
  assert.match(page, /checked=\{form\.isAdmin\}/);
  assert.match(page, /Profesores editores/);
  assert.match(page, /form\.editorIds\.includes\(teacher\.id\)/);
  assert.match(page, /Editor \{code\}/);
  assert.match(page, /editableSubjectIds/);
  assert.match(page, /hasSubjectEditorRole/);
  assert.match(page, /canEditSession/);
  assert.match(page, /Asignatura a la que se vincula/);
  assert.match(styles, /\.subject-editor-tag/);
  assert.match(styles, /\.permission-tag\.editor/);
  assert.match(styles, /\.editor-picker-help/);
  assert.match(page, /canDelete=\{authenticatedTeacher\.isAdmin\}/);
  assert.match(page, /Modo de solo lectura/);
  assert.match(page, /Iniciar sesión/);
  assert.match(page, /He olvidado mi contraseña/);
  assert.match(page, /Recuperar acceso/);
  assert.match(page, /Revisa tu correo/);
  assert.match(page, /Nueva contraseña/);
  assert.match(page, /api\/auth\/password-reset\/request/);
  assert.match(page, /api\/auth\/password-reset\/reset/);
  assert.doesNotMatch(page, /mailto:/);
  assert.match(styles, /\.recovery-result/);
  assert.match(packageJson, /"nodemailer"/);
  assert.match(page, /type="password"/);
  assert.match(page, /Nueva contraseña/);
  assert.match(page, /api\/auth\/session/);
  assert.match(page, />Salir</);
  assert.match(page, /teacher\.email \|\| "Sin correo electrónico"/);
  assert.match(page, /Prof\. \{session\.teacherName \?\? session\.teacherCode \?\? "sin asignar"\}/);
  assert.match(page, /weekly-teacher-name/);
  assert.match(page, /weekly-teacher-code/);
  assert.match(page, /function sessionPracticeTitle\(session: Session\)/);
  assert.match(page, /session\.practiceOrder \? `P\$\{session\.practiceOrder\} ` : ""/);
  assert.match(page, /`\$\{prefix\}\$\{session\.practiceName\} · \$\{session\.practiceCode\}`/);
  assert.match(page, /<strong>\{sessionPracticeTitle\(session\)\}<\/strong>/);
  assert.match(page, /title=\{sessionPracticeTitle\(session\)\}>\{sessionPracticeTitle\(session\)\}/);
  assert.match(styles, /container: weekly-session \/ inline-size/);
  assert.match(styles, /@container weekly-session \(max-width: 190px\)/);
  assert.match(page, /sort\(compareTeachersBySurname\)/);
  assert.match(await readFile(new URL("../app/api/data/route.ts", import.meta.url), "utf8"), /localeCompare\(String\(right\), "es", \{ sensitivity: "base" \}\)/);
  assert.match(await readFile(new URL("../app/api/data/route.ts", import.meta.url), "utf8"), /ORDER BY p\.name COLLATE NOCASE, p\.code COLLATE NOCASE/);
  assert.match(await readFile(new URL("../app/api/data/route.ts", import.meta.url), "utf8"), /compareSpanish\(left\.name, right\.name\)[\s\S]*?compareSpanish\(left\.code, right\.code\)/);
  assert.match(await readFile(new URL("../lib/database.ts", import.meta.url), "utf8"), /migrateRequestedSessionTimes[\s\S]*?code = '30013'[\s\S]*?code = '30018'/);
  assert.match(await readFile(new URL("../lib/database.ts", import.meta.url), "utf8"), /migrateRequested29716SessionDurations[\s\S]*?duration = 180[\s\S]*?code = '29716'/);
  assert.match(page, /function comparePracticesByName[\s\S]*?left\.name\.localeCompare\(right\.name[\s\S]*?left\.code\.localeCompare\(right\.code/);
  assert.match(page, /function practiceOptionLabel\(practice: Practice, position\?: number \| null\)[\s\S]*?P\$\{position\}[\s\S]*?\$\{practice\.name\} · \$\{practice\.code\}/);
  assert.match(page, /function practicesAvailableToSessions[\s\S]*?\.sort\(comparePracticesByName\)/);
  assert.match(page, /const subjectPracticePositions = selectedSubject[\s\S]*?selectedSubject\.practiceIds\.map[\s\S]*?subjectPracticePositions\.get\(left\.id\)/);
  assert.ok(page.match(/practiceOptionLabel\(practice,/g)?.length >= 3);
  assert.match(page, /const orderedPractices = useMemo[\s\S]*?sort\(comparePracticesByName\)/);
  assert.match(page, /const filterPractices = useMemo[\s\S]*?selectedSubject\.practiceIds\.map\(Number\)[\s\S]*?positions\.get\(left\.id\)/);
  assert.match(page, /filterPractices\.map\(\(practice\) => \{[\s\S]*?practiceOptionLabel\(practice, practicePositionInSubject/);
  assert.match(page, /Todas las prácticas de la asignatura/);
  assert.match(page, /orderedPractices\.map\(\(practice\) =>/);
  assert.match(page, /const sessionPracticeOptions = \(selectedSessionSubject\?\.practiceIds \?\? \[\]\)/);
  assert.match(page, /Orden de las prácticas seleccionadas/);
  assert.match(page, /moveSelectedPractice/);
  assert.match(styles, /\.subject-practice-order-row/);
  assert.match(page, /teacherId/);
  assert.match(page, /teacherSessionCounts/);
  assert.match(page, /semesterFromDate\(session\.sessionDate\) !== selectedSemester/);
  assert.match(page, /Sesiones del semestre/);
  assert.match(page, /Cambiar semestre para el recuento de profesores/);
  assert.match(page, /semesterSessionCount/);
  assert.match(styles, /\.teacher-semester-toolbar/);
  assert.match(page, /installationIds/);
  assert.match(page, /subjectId/);
  assert.match(page, /Editar/);
  assert.doesNotMatch(page, /edit-button/);
  assert.equal([...page.matchAll(/\? "[^"]*editable-record[^"]*"/g)].length, 6);
  assert.match(page, /function editRecordWithKeyboard/);
  assert.match(page, /event\.target !== event\.currentTarget/);
  assert.match(page, /event\.stopPropagation\(\); onDelete/);
  assert.match(styles, /\.editable-record/);
  assert.match(styles, /\.read-only-badge/);
  assert.match(styles, /\.permission-checkbox/);
  assert.match(styles, /\.permission-tag\.admin/);
  assert.match(styles, /\.entity-table tr\.editable-record:hover td/);
  assert.match(page, /Calendario de sesiones/);
  assert.match(page, /sessionPracticeId/);
  assert.match(page, /Importar ICS/);
  assert.match(page, /Importar asignación sesiones/);
  assert.match(page, /canEdit && \([\s\S]*?Importar asignación sesiones/);
  assert.match(page, /function SessionAssignmentImportDialog/);
  assert.match(page, /Hay \{preview\.alreadyAssignedCount\}[\s\S]*?¿Qué quieres hacer\?/);
  assert.match(page, /Conservar asignaciones existentes/);
  assert.match(page, /Aplicar las asignaciones del CSV/);
  assert.match(page, /\/api\/import\/session-assignments/);
  assert.match(styles, /\.assignment-conflict-options/);
  const assignmentImportRoute = await readFile(new URL("../app/api/import/session-assignments/route.ts", import.meta.url), "utf8");
  assert.match(assignmentImportRoute, /authenticatedTeacher\.isAdmin/);
  assert.match(assignmentImportRoute, /keep-existing/);
  assert.match(assignmentImportRoute, /overwrite-existing/);
  assert.match(page, /Prácticas de laboratorio/);
  assert.match(page, /SUMMARY comienza por “Día festivo”/);
  assert.match(page, /preview\.holidayCount/);
  assert.match(page, /calendar-holiday-label/);
  assert.match(page, /academicDayTypes/);
  assert.match(page, /academicWeekdayLabel/);
  assert.match(page, /calendar-day-type/);
  assert.match(page, /holidaysByDate/);
  assert.match(page, /sessionDateBlocked/);
  assert.match(page, /Esta fecha es festiva/);
  assert.match(page, /event\.dataTransfer\.dropEffect = "none"/);
  assert.match(page, /Día festivo · no se pueden programar sesiones/);
  assert.match(page, /holidayConflictCount/);
  assert.match(styles, /\.calendar-day\.holiday/);
  assert.match(styles, /\.calendar-day-type/);
  assert.match(styles, /\.calendar-week-column\.holiday/);
  assert.match(page, /El código de cinco dígitos de SUMMARY identifica la asignatura/);
  assert.match(page, /Grupos detectados/);
  assert.match(page, /el número que sigue a “Grupo:” se guarda en cada sesión/);
  assert.match(page, /Sin profesor asignado/);
  assert.match(page, /Profesor \(opcional\)/);
  assert.match(page, /Sin práctica asignada/);
  assert.match(page, /required=\{editingId === null\}/);
  assert.match(page, /editingId !== null \|\| subject\.practiceIds\.length > 0/);
  assert.match(page, /duration: editingId !== null && practice \? String\(practice\.duration\) : form\.duration/);
  assert.match(page, /También se creará el grado/);
  assert.match(page, /Importación completada/);
  assert.match(page, /Se importó una sesión nueva sin práctica asignada/);
  assert.match(page, /createdCount === 1 \? "creó" : "crearon"/);
  assert.match(page, /Incompleta: sin práctica/);
  assert.match(page, /Shift \+ clic/);
  assert.doesNotMatch(page, /onContextMenu/);
  assert.match(page, /Asignar profesor/);
  assert.match(page, /Asignar práctica/);
  assert.match(page, /barra de acciones/);
  assert.match(page, /action: "assign-teacher"/);
  assert.match(styles, /\.session-selection-actions/);
  assert.doesNotMatch(styles, /\.practice-context-menu/);
  assert.match(page, /Semestre académico/);
  assert.match(page, /availableSemesters/);
  assert.match(page, /onSelectedSemesterChange/);
  assert.match(page, /Borrar semestre/);
  assert.match(page, /Borrar selección/);
  assert.match(page, /onDeleteSessions/);
  assert.match(page, /sessions: data\.sessions\.filter\(\(session\) => semesterFromDate\(session\.sessionDate\) === selectedSemester\)\.length/);
  assert.doesNotMatch(page, /Sesiones por asignatura/);
  assert.match(page, /Filtrar por laboratorio/);
  assert.match(page, /Filtrar por instalación/);
  assert.match(page, /Filtrar por grado/);
  assert.match(page, /Filtrar por asignatura/);
  assert.match(page, /const filterSubjects = useMemo/);
  assert.match(page, /subjects\.filter\(\(subject\) => String\(subject\.degreeId\) === filters\.degreeId\)/);
  assert.match(page, /degreeId: value, subjectId: "", practiceId: ""/);
  assert.match(page, /Todas las asignaturas del grado/);
  assert.match(page, /filterSubjects\.map\(\(subject\)/);
  assert.match(page, /Filtrar por práctica/);
  assert.match(page, /Limpiar filtros/);
  assert.match(page, /Vista del calendario/);
  assert.match(page, /calendarView === "week" \? "semanal" : "en lista"/);
  assert.match(page, /changeCalendarView\("list"\)\}>Lista/);
  assert.match(page, /sessionsByDate\.entries\(\)/);
  assert.match(page, /dateSessions\.map\(renderListSession\)/);
  assert.match(page, /ordenadas cronológicamente/);
  assert.match(page, /calendar-list-select-indicator/);
  assert.match(styles, /\.calendar-list-session/);
  assert.match(styles, /\.calendar-list-session\.selected/);
  assert.match(page, /calendarWeekStartHour = 8/);
  assert.match(page, /calendarWeekEndHour = 19/);
  assert.match(page, /calendarWeekDayCount = 5/);
  assert.match(page, /Array\.from\(\{ length: calendarWeekDayCount \}/);
  assert.match(page, /repeat\(\$\{weekDays\.length\}/);
  assert.doesNotMatch(styles, /calendar-week-grid[^}]*repeat\(7/);
  assert.match(page, /Vista semanal de 08:00 a 19:00/);
  assert.match(page, /layoutOverlappingSessions/);
  assert.match(page, /overlapping-session/);
  assert.match(page, /weeklyLayout\.maximumLaneCount/);
  assert.match(page, /Arrastra una sesión para cambiar su día y hora/);
  assert.match(page, /onDragStart/);
  assert.match(page, /onDrop/);
  assert.match(page, /Soltar aquí/);
  assert.match(page, /session-drag-image/);
  assert.match(page, /calendar-month-drop-preview/);
  assert.match(page, /monthly-session-line/);
  assert.match(page, /subjectAbbreviation \|\| session\.subjectCode/);
  assert.match(page, /session\.startTime\.replace\(\/\^0\//);
  assert.match(styles, /\.monthly-session-line strong \{ margin: 0 7px; font-size: 11px;/);
  assert.match(page, /weekly-practice-name/);
  assert.match(page, /sessionPracticeTitle\(session\)/);
  assert.match(page, /session-teacher-unassigned/);
  assert.match(page, /Prof\. sin asignar/);
  assert.match(styles, /\.session-teacher-unassigned \{ color: var\(--danger\)/);
  assert.match(styles, /\.weekly-practice-name, \.weekly-session-details/);
  await assert.rejects(access(new URL("../.openai/hosting.json", import.meta.url)));
});
